const express = require('express');
const router = express.Router();
const nsfPerformanceController = require('../controllers/nsfPerformanceController');

// ============================================================================
// CRYSTAL REPORTS & REPORT MANAGEMENT ROUTES (Specific routes FIRST)
// ============================================================================

/**
 * @route   GET /api/nsf-performance/report-health
 * @desc    Check health status of Crystal Reports generation system
 * @access  Public
 * @returns JSON health status including Crystal Reports template and directories
 */
router.get('/nsf-performance/report-health', nsfPerformanceController.reportSystemHealth);

/**
 * @route   GET /api/nsf-performance/reports
 * @desc    List all available PDF reports generated by Crystal Reports
 * @access  Public
 * @returns JSON array of report files with metadata
 */
router.get('/nsf-performance/reports', nsfPerformanceController.listReports);

/**
 * @route   GET /api/nsf-performance/reports/:filename
 * @desc    Serve a specific Crystal Reports PDF file
 * @access  Public
 * @param   filename - Name of the PDF file to serve
 * @returns PDF file stream
 */
router.get('/nsf-performance/reports/:filename', nsfPerformanceController.serveReport);

/**
 * @route   GET /api/nsf-performance/generate-report
 * @desc    Generate NSF Performance PDF report using Crystal Reports
 * @access  Public
 * @query   submid, dateFrom, dateTo
 * @returns Crystal Reports PDF file stream
 * @example GET /api/nsf-performance/generate-report?submid=123&dateFrom=2024-01-01&dateTo=2024-01-31
 */
router.get('/nsf-performance/generate-report', nsfPerformanceController.generateNsfReport);

/**
 * @route   GET /api/nsf-performance/lab-details
 * @desc    Get NSF Performance Lab Details by submid and date range
 * @access  Public
 * @query   submid, dateFrom, dateTo
 * @returns JSON with lab details data
 */
router.get('/nsf-performance/lab-details', nsfPerformanceController.getNsfPerformanceLabDetails);

// ============================================================================
// DATA QUERY ROUTES (General route should be LAST)
// ============================================================================

/**
 * @route   GET /api/nsf-performance
 * @desc    Get NSF Performance data by county and date range
 * @access  Public
 * @query   county, dateFrom, dateTo
 * @returns JSON with NSF performance statistics
 * @example GET /api/nsf-performance?county=batangas&dateFrom=2024-01-01&dateTo=2024-01-31
 */
router.get('/nsf-performance', nsfPerformanceController.getNsfPerformance);

// ============================================================================
// ERROR HANDLING MIDDLEWARE
// ============================================================================

/**
 * Handle 404 errors for this router
 */
router.use((req, res) => {
    res.status(404).json({
        success: false,
        error: 'NSF Performance endpoint not found',
        path: req.originalUrl,
        availableEndpoints: [
            'GET /api/nsf-performance?county=<county>&dateFrom=<YYYY-MM-DD>&dateTo=<YYYY-MM-DD>',
            'GET /api/nsf-performance/lab-details?submid=<submid>&dateFrom=<YYYY-MM-DD>&dateTo=<YYYY-MM-DD>',
            'GET /api/nsf-performance/generate-report?submid=<submid>&dateFrom=<YYYY-MM-DD>&dateTo=<YYYY-MM-DD>',
            'GET /api/nsf-performance/reports',
            'GET /api/nsf-performance/reports/<filename>',
            'GET /api/nsf-performance/report-health'
        ],
        generator: 'Crystal Reports'
    });
});

module.exports = router;